# Generated by Django 5.2.3 on 2025-07-01 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-attempted_at'], 'verbose_name': 'Login Attempt', 'verbose_name_plural': 'Login Attempts'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-login_time'], 'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', 'attempted_at'], name='auth_logina_usernam_c1d75b_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', 'attempted_at'], name='auth_logina_ip_addr_1ec098_idx'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_customuser',
        ),
        migrations.AlterModelTable(
            name='loginattempt',
            table='auth_loginattempt',
        ),
        migrations.AlterModelTable(
            name='usersession',
            table='auth_usersession',
        ),
    ]
