# Generated by Django 5.2.3 on 2025-06-22 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single Room'), ('DOUBLE', 'Double Room'), ('SUITE', 'Suite'), ('DELUXE', 'Deluxe Room')], max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('max_occupancy', models.IntegerField(default=2)),
                ('amenities', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=15)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_guests', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_bookings', to=settings.AUTH_USER_MODEL)),
                ('guest_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_panel_booking_profile', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.room')),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('ROOM_CLEANLINESS', 'Room Cleanliness'), ('AC_HEATING', 'AC/Heating Issue'), ('PLUMBING', 'Plumbing Issue'), ('ELECTRICAL', 'Electrical Issue'), ('NOISE', 'Noise Complaint'), ('ROOM_SERVICE', 'Room Service'), ('WIFI', 'WiFi/Internet Issue'), ('MAINTENANCE', 'General Maintenance'), ('OTHERS', 'Others')], max_length=50)),
                ('detailed_description', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='grievance_attachments/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.booking')),
                ('guest', models.ForeignKey(limit_choices_to={'role': 'GUEST'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_grievances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=100)),
                ('supervisor_phone', models.CharField(max_length=15)),
                ('worker_name', models.CharField(max_length=100)),
                ('worker_phone', models.CharField(max_length=15)),
                ('parts_replaced_fixed', models.TextField()),
                ('product_replaced', models.CharField(blank=True, max_length=200)),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_invoice_pic', models.ImageField(blank=True, null=True, upload_to='maintenance_bills/')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_worker', models.ForeignKey(limit_choices_to={'role': 'MAINTENANCE'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_assigned_work', to=settings.AUTH_USER_MODEL)),
                ('grievance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.grievance')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'MAINTENANCE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
